mysqlConfig = {
    "MYSQL_ADDON_HOST": "<INSERT MYSQL HOST HERE>",
    "MYSQL_ADDON_DB": "<INSERT MYSQL DB NAME HERE>",
    "MYSQL_ADDON_USER": "<INSERT MYSQL DB USERNAME HERE>",
    "MYSQL_ADDON_PORT": 3306,
    "MYSQL_ADDON_PASSWORD": "<INSERT MYSQL DB PASSWORD HERE>",
    "MYSQL_ADDON_URI": "<INSERT MYSQL DB PASSWORD HERE>",
}
